export const departmentData = {
    ce: {
      name: 'Department of Civil Engineering',
      faculty: [
        { name: 'Engr. Radger Teddy Manuel', position: 'Program Chair, Civil Engineering', },
        { name: 'Engr. Romualdo Caluag', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. Joyce Evangelista', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. Sarah Faustino', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. Renato Gopez', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. Merricris Pangilinan', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. Jennie Roque', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. Florence Samonte', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. June-june Santos', position: 'Faculty, Civil Engineering' },
        { name: 'Engr. Maureen Therese Balayan', position: 'Part-time Instructor, Civil Engineering' },
        { name: 'Engr. Ace Dhenniel V. Daria', position: 'Part-time Instructor, Civil Engineering' },
        { name: 'Engr. Cecilia A.  Geronimo', position: 'Part-time Instructor, Civil Engineering' },
        { name: 'Engr. Rondolf Lobo', position: 'Part-time Instructor, Civil Engineering' },
        { name: 'Engr. Marbel Perez', position: 'Part-time Instructor, Civil Engineering' },
      ],
    },
    cse: {
      name: 'Department of Computer Engineering',
      faculty: [
          { name: 'Engr. Alexander M. Aquino', position: 'Faculty, Computer Engineering', imageUrl: 'https://scontent.fmnl33-6.fna.fbcdn.net/v/t39.30808-6/432001437_7818125638232002_5562765456735340087_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=1d70fc&_nc_eui2=AeHx5IBl2lDFQVjCj9lQ1JBJpsKTRh6ZHbWmwpNGHpkdtUYwN_O2x72GwVYJ6i3lh1vfg21q6IeKl_hGPtyh-ebf&_nc_ohc=5bAM7fll7PgQ7kNvwGWjd6v&_nc_oc=Adrk190VNuwf8fiUQYf5_AlqwdeXe-bpxgXkLM4h2RKhubV_EiLI7IM7pJ9mJLvX7IU&_nc_zt=23&_nc_ht=scontent.fmnl33-6.fna&_nc_gid=18TnosGx-p3wJ7bS_G0x5A&_nc_ss=8&oh=00_Afz9yeWL77vpc3Kxfpna9YBrUUIaLcEViQOFdPgqXKEhpA&oe=69C1B336' },
          { name: 'Dr. Lech Walesa M. Navarra', position: 'Faculty, Computer Engineering', imageUrl: 'https://tse2.mm.bing.net/th/id/OIP.988VN0zeTzZi_adocVOzlgHaF9?rs=1&pid=ImgDetMain&o=7&rm=3' },
          { name: 'Engr. Maria Lorena SP. Villena', position: 'Faculty, Computer Engineering', imageUrl: 'https://scontent.fmnl33-6.fna.fbcdn.net/v/t39.30808-6/518273578_10161964891223089_1387706342810050150_n.jpg?stp=cp6_dst-jpg_tt6&_nc_cat=109&ccb=1-7&_nc_sid=53a332&_nc_eui2=AeH_CznqgIzo6NSaSFgi2d4aN6swz8I1lGg3qzDPwjWUaIahXUQbrhWogO75Vp7GRqbwUw-mZobKJutHJ0YTs_6S&_nc_ohc=POoOU7YD0QQQ7kNvwGGZKCZ&_nc_oc=Adorc_O5zDdFe4hpC8OJti5XgUFr6R4XLq5JTTx-fV0jgSaRpTMghR4_sBa6J2-ZsV8&_nc_zt=23&_nc_ht=scontent.fmnl33-6.fna&_nc_gid=y2HgmSkGMMsGbg7iMfFa5Q&_nc_ss=8&oh=00_AfxPe79Q5yGQ0CUt71DKP9arnwpwMKTkcHmtTRoL0I7_VQ&oe=69C1B22E' },
          { name: 'Engr. Bernard G. Yasay', position: 'Faculty, Computer Engineering', imageUrl: 'https://scontent.fmnl33-1.fna.fbcdn.net/v/t1.6435-9/106900367_3221451041208387_3429629015504058937_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=53a332&_nc_eui2=AeHreREWUcg8CPpc2n9233ICUfmKCdhOHdBR-YoJ2E4d0KSl8ElThT2JSc_VTm50pCgh_0yiIvG4L2tQe8PWMNtJ&nc_ohc=fXIcYaqW8SMQ7kNvwGCRzl3&_nc_oc=Adq5bHDK4BtlzTbCuMmFoKpqegF27CIc5jldw9KN1bReK2YYQtnjPMsx5pdN9scJblg&_nc_zt=23&_nc_ht=scontent.fmnl33-1.fna&_nc_gid=-utV-ZYSdd5EjaqCPsmPtA&_nc_ss=8&oh=00_Afz9HP5j32iMFG_wOgv-ZTjBrgkx38L5dnFAh-tGMOFYlg&oe=69E35517'},
          { name: 'Engr. Catherine V. Dela Cruz', position: 'Faculty, Computer Engineering' },
          { name: 'Engr. Richard Y. Dela Cruz', position: 'Faculty, Computer Engineering' },
          { name: 'Dr. Ma. Magdalena V. Gatdula', position: 'Faculty, Computer Engineering'},
          { name: 'Dr. Monaliza S. Jimenez', position: 'Faculty, Computer Engineering', imageUrl: 'https://scontent.fmnl33-6.fna.fbcdn.net/v/t39.30808-6/506539339_10232965089962514_5933195125117214841_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=53a332&_nc_eui2=AeGMJztwon0WiLBUYCxRDu5yXNjtmgBjaRVc2O2aAGNpFdLp4QIeSmaW7ha8sJ7ntHdk-RQRxUt0HpHjRNvLHPT8&nc_ohc=dqJMXyHzPQAQ7kNvwHkOMn_&_nc_oc=AdpVi-j_E6K9dzSQmJVAaNbR1hiUVfhrlbgHZZ6p9xAQHx493UvVv0yHPMNUxuMYxpU&_nc_zt=23&_nc_ht=scontent.fmnl33-6.fna&_nc_gid=-ce7GL_ZmrPltW5dkLRroQ&_nc_ss=8&oh=00_AfwFHfTOqAIncovNdPDQWEqd_8r6WCH6yYP5s0KeyjhK_g&oe=69C19ECC' },
          { name: 'Engr. Julius Vincent M. Abanel', position: 'Part-Time Instructor, Computer Engineering' },
          { name: 'Engr. Hiroyoshi  DG. Arai', position: 'Part-Time Instructor, Computer Engineering' },
          { name: 'Engr. Robert Justin S. Chavez', position: 'Part-Time Instructor, Computer Engineering' },
          { name: 'Engr. Albert C. Cruz Jr.', position: 'Part-Time Instructor, Computer Engineering' },
          { name: 'Engr. Maria Ana G. Dangan', position: 'Guest Lecturer, Computer Engineering' },  
          { name: 'Engr. Sheila May M. Liwag', position: 'Guest Lecturer, Computer Engineering' },
      ],
    },
    ece: {
      name: 'Department of Electronics Engineering',
      faculty: [
          { name: 'Engr. Donald M. Lapiguera', position: 'Program Chair, Electronics Engineering' },
          { name: 'Engr. Mervin E. Albalate', position: 'Faculty, Electronics Engineering' },
          { name: 'Dr. Russell N. Alfonso', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Hilario A. Calinao Jr.', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Jenette C. Centeno', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Dennis R. dela Cruz', position: 'Faculty, Electronics Engineering' },
          { name: 'Dr. Reagan L. Galvez, PECE', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Albert Ian R. Javier', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Nasher G. Jimenez, PECE', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Amor A. Lacara', position: 'Faculty, Electronics Engineering' },
          { name: 'Dr. Marlon C. Leyesa, PECE', position: 'Faculty, Electronics Engineering' },
          { name: 'Prof. Oliver R. Mariano, PECE, ASEAN Engr.', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Dion Michael M. Mendoza', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Paul Ryan A. Santiago', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Rina S.P. Santiago', position: 'Faculty, Electronics Engineering' },
          { name: 'Engr. Jeffrey V. Cayetano', position: 'Part-time Instructor, Electronics Engineering' },
          { name: 'Engr. Nemuel Norman F. Giron', position: 'Part-time Instructor, Electronics Engineering' },
          { name: 'Engr. Evangelyn C. Samson', position: 'Part-time Instructor, Electronics Engineering' },
          { name: 'Engr. Benjamin L. Santa maria, jr.', position: 'Part-time Instructor, Electronics Engineering' },
          { name: 'Engr. Christian S. Fajardo, PECE, ASEAN Engr.', position: 'Industrial Lecturer, Electronics Engineering' },
          { name: 'Engr. Richard R. Garcia, PECE, ASEAN, ACPE, APEC Engr.', position: 'Industrial Lecturer, Electronics Engineering' },
      ],
    },
    eee: {
      name: 'Department of Electrical Engineering',
      faculty: [
          { name: 'Engr. Arjay R. Alba', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Dennis L. Aguirre', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Reynaldo C. Alejandria', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Ronan Cadmiel C. Castro', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Jovita SP. Domingo', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Riah Ann DR. Fermin-Cayanan', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Mark Adrian R. Lunaria', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Eleazer C. Nabong', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. Allan Clark H. Timoteo', position: 'Faculty, Electrical Engineering' },
          { name: 'Engr. John Byrone A. Clavio', position: 'Part-time Instructor, Electrical Engineering' },
          { name: 'Engr. Mark Louie D. Martinez', position: 'Part-time Instructor, Electrical Engineering' },
          { name: 'Engr. Rogelio C. Pimentel', position: 'Part-time Instructor, Electrical Engineering' },
          { name: 'Engr. Anthony T. Reyes', position: 'Part-time Instructor, Electrical Engineering' },
          { name: 'Engr. Ronel I. Serrano', position: 'Part-time Instructor, Electrical Engineering' },
          { name: 'Engr. Diane H. Villanueva', position: 'Part-time Instructor, Electrical Engineering' },
          { name: 'Engr. Nhowel F. Jimenez', position: 'Part-time Instructor, Electrical Engineering' },
          { name: 'Engr. John Paul V. Dela Cruz', position: 'Industry Lecturer, Electrical Engineering' },
      ],
    },
    ie: {
      name: 'Department of Industrial Engineering',
      faculty: [
          { name: 'Engr. Jeremy Laurence M. Bañez, MSIE, CIE, Assoc. ASEAN Eng.', position: 'Program Chair, Industrial Engineering' },
          { name: 'Engr. Marianne B. Calayag, MSMfE, PIE, ASEAN Eng.', position: 'Faculty, Industrial Engineering' },
          { name: 'Engr. Hazel A. Caparas, MSIE, PIE, ASEAN Eng.', position: 'Faculty, Industrial Engineering' },
          { name: 'Dr. Rick Donald S. Manzon, PhD-Eng Mgt, MSIE, PIE', position: 'Faculty, Industrial Engineering' },
          { name: 'Engr. Ivy Mar J. Ramos, MBA, PIE, ASEAN Eng.', position: 'Faculty, Industrial Engineering' },
          { name: 'Engr. Dyan G. Rodriguez, MSIE, PIE, ASEAN Eng.', position: 'Faculty, Industrial Engineering' },
          { name: 'Engr. Christian Lance P. Arojado', position: 'Part-time Instructor, Industrial Engineering' },
          { name: 'Engr. Steven C. Co, Jr., CIE, Assoc. ASEAN Eng.', position: 'Part-time Instructor, Industrial Engineering' },
          { name: 'Engr. Raph John P. Miranda, CIE', position: 'Part-time Instructor, Industrial Engineering' },
          { name: 'Engr. Juan C. Tecson, LLB, PIE', position: 'Part-time Instructor, Industrial Engineering' },
          { name: 'Engr. Jasper Kevin C. Dionisio, CIE, Assoc. ASEAN Eng.', position: 'Industry Lecturer, Industrial Engineering' },
      ],
    },
    mfe: {
        name: 'Department of Manufacturing Engineering',
        faculty: [
            { name: 'Engr. Romano A. Gabrillo', position: 'Program Chair, Manufacturing Engineering' },
            { name: 'Engr. Nancy M. Santiago', position: 'Faculty, Manufacturing Engineering' },
            { name: 'Engr. Cyrus Lawrence C. Bual', position: 'Faculty, Manufacturing Engineering' },
            { name: 'Engr. Rachel C. Bual', position: 'Faculty, Manufacturing Engineering' },
            { name: 'Engr. Nasher G. Jimenez, PECE', position: 'Faculty, Manufacturing Engineering' },
            { name: 'Engr. Jayvee L. Jimenez', position: 'Part-time Instructor, Manufacturing Engineering' },
            { name: 'Engr. Precious Rose F. Galvez', position: 'Part-time Instructor, Manufacturing Engineering' },
        ]
    },
    me: {
      name: 'Department of Mechanical Engineering',
      faculty: [
          { name: 'Engr. Adrian C. Flores', position: 'Faculty, Mechanical Engineering' },
          { name: 'Engr. Aldrin C. Bernardo', position: 'Faculty, Mechanical Engineering' },
          { name: 'Engr. Boris R. Palao', position: 'Faculty, Mechanical Engineering' },
          { name: 'Engr. Felizardo S. Camilon Jr.', position: 'Faculty, Mechanical Engineering' },
          { name: 'Engr. Ian Jay T. Matias', position: 'Faculty, Mechanical Engineering' },
          { name: 'Engr. Romulo B. Panotes Jr.', position: 'Faculty, Mechanical Engineering' },
          { name: 'Engr. Amparo Cecilia DS. Sarmiento', position: 'Part-Time Instructor, Mechanical Engineering' },
          { name: 'Engr. Haivell Joy C. Matias', position: 'Part-Time Instructor, Mechanical Engineering' },
          { name: 'Engr. Arren B. Santos', position: 'Part-Time Instructor, Mechanical Engineering' },
          { name: 'Engr. Audie L. Geronimo', position: 'Part-Time Instructor, Mechanical Engineering' },
          { name: 'Engr. Zedrick T. Farin', position: 'Part-Time Instructor, Mechanical Engineering' },
          { name: 'Engr. Aeron Cris C. Pacis', position: 'Industry Lecturer, Mechanical Engineering' },
          { name: 'Engr. Earl Jan L. Santos', position: 'Guest Lecturer, Mechanical Engineering' },
      ],
    },
    mce: {
        name: 'Department of Mechatronics Engineering',
        faculty: [
          { name: 'Engr. Arvin Julius S. Tullao', position: 'Program Chair, Mechatronics Engineering' },
          { name: 'Engr. Nasher G. Jimenez, PECE', position: 'Faculty, Mechatronics Engineering' },
          { name: 'Engr. Gabriel Angelo V. Pascual', position: 'Part-Time Instructor, Mechatronics Engineering' },
          { name: 'Engr. Al Justin S. Geronimo', position: 'Part-Time Instructor, Mechatronics Engineering' },
          { name: 'Engr. Jerome B. Bagsic', position: 'Part-Time Instructor, Mechatronics Engineering' },
          { name: 'Engr. Juan Martin R. Cruz', position: 'Part-Time Instructor, Mechatronics Engineering' },
          { name: 'Engr. Reggiel Clint L. Valdez', position: 'Part-Time Instructor, Mechatronics Engineering' },
          { name: 'Engr. Jason D. Lozano', position: 'Part-Time Instructor, Mechatronics Engineering' },
          { name: 'Engr. John Darwin P. Quintal', position: 'Part-Time Instructor, Mechatronics Engineering' },
        ]
    },
  };
  